version: "3.8"
services:
  app:
    build: ..
    volumes:
      - .:/code
    ports:
      - 8001:8001
    image: app:iha
    container_name: django_container2
    command: python manage.py runserver 0.0.0.0:8001