# Generated by Django 4.2 on 2023-04-25 12:22

from django.db import migrations, models
import iha_project.common.fileUpload.userDirectoryPath


class Migration(migrations.Migration):

    dependencies = [
        ('iha_project', '0002_model_model_brand_alter_model_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iha',
            old_name='height',
            new_name='weight',
        ),
        migrations.AddField(
            model_name='iha',
            name='img',
            field=models.ImageField(default='', upload_to=iha_project.common.fileUpload.userDirectoryPath.userDirectoryPath, verbose_name='Iha resmi'),
            preserve_default=False,
        ),
    ]
