# Generated by Django 4.2 on 2023-04-25 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iha_project', '0003_rename_height_iha_weight_iha_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iha_project.category', verbose_name='Kategori'),
        ),
    ]
