# Generated by Django 4.2 on 2023-04-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iha_project', '0004_alter_iha_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iha_project.brand', verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='iha',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iha_project.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='iha',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iha_project.model', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iha_project.brand', verbose_name='Model'),
        ),
    ]
