# Generated by Django 4.2 on 2023-04-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iha_project', '0005_alter_iha_brand_alter_iha_category_alter_iha_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model_name',
            new_name='name',
        ),
    ]
