# Generated by Django 3.2.18 on 2023-04-26 05:10

from django.db import migrations, models
import django.db.models.deletion
import iha_project.common.fileUpload.userDirectoryPath


class Migration(migrations.Migration):

    dependencies = [
        ('iha_project', '0007_auto_20230425_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iha_project.brand', verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='iha',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=iha_project.common.fileUpload.userDirectoryPath.userDirectoryPath, verbose_name='Iha resmi'),
        ),
        migrations.AlterField(
            model_name='iha',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iha_project.model', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='iha',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ağırlık'),
        ),
    ]
